#' Format DCPO Data for Estimation Using DCPO Stan Files
#'
#'  \code{format_dcpo} formats DCPO data output by \code{dcpo_setup} for use with the \code{DCPO}
#'  package's \code{dcpo} Stan files.
#'
#' @param dcpo_data a data frame of survey responses generated by \code{dcpo_setup}
#'
#' @return a list of Stan data
#'
#' @import dplyr
#' @importFrom reshape2 dcast
#' @importFrom tibble rownames_to_column
#' @importFrom janitor clean_names
#'
#' @export

format_dcpo <- function(x, scale_item, scale_cp) {
    # satisfy R CMD check
    country <- year <- item <- r <- n <- NULL

    # generate cumulative number of respondents with answers above each cutpoint
    dat <- x %>%
        group_by(country, year, item) %>%
        arrange(desc(r), .by_group = TRUE) %>%
        mutate(item_c = paste(item, r, "or higher"),
               y_r = round(cumsum(n)),
               n_r = round(sum(n)),
               cp = r - 1) %>%
        arrange(r, .by_group = TRUE) %>%
        ungroup() %>%
        filter(y_r > 0 & cp > 0)

    n_qr <- reshape2::dcast(dat,
                            item ~ cp,
                            fun.aggregate = sum,
                            value.var = "n",
                            drop = FALSE) %>%
        tibble::rownames_to_column()

    scale_item_matrix <- n_qr %>%
        janitor::clean_names() %>%
        mutate_at(vars(matches(paste0("x\\d+$"))), ~if_else(. > 0, 10, 0)) %>%
        mutate_at(vars(matches(paste0("x", scale_cp, "$"))), ~if_else(item == scale_item, . + 1, 0)) %>%
        mutate_at(vars(matches(paste0("x\\d+$"))), ~if_else(. > 0, . - 10, 0)) %>%
        select(-rowname, -item) %>%
        as.matrix()
    stopifnot(sum(scale_item_matrix) == 1)

    dcpo_stan <- list( K          = dplyr::n_distinct(dat$country),
                       T          = max(dat$year) - min(dat$year) + 1,
                       Q          = dplyr::n_distinct(dat$item),
                       R          = max(dat$cp),
                       P          = max(as.numeric(as.factor(paste(dat$country, dat$item)))),
                       N          = nrow(dat),
                       kk         = as.numeric(as.factor(dat$country)),
                       tt         = as.numeric(as.factor(dat$year)),
                       qq         = as.numeric(as.factor(dat$item)),
                       rr         = dat$cp,
                       pp         = as.numeric(as.factor(paste(dat$country, dat$item))),
                       y_r        = round(dat$y_r),
                       n_r        = round(dat$n_r),
                       fixed_cutp = scale_item_matrix,
                       data       = dat)

    return(dcpo_stan)
}
