#' Format DCPO Data for Estimation Using Claassen's (2019) Stan Files
#'
#'  \code{format_claassen} formats DCPO data output by \code{dcpo_setup} for use with Claassen's
#'  Stan files for "Estimating Smooth Country-Year Panels for Public Opinion" (_Political Analysis_,
#'  2019).
#'
#' @param dcpo_data a data frame of survey responses generated by \code{dcpo_setup}
#'
#' @details  \code{format_claassen} formats DCPO data output by \code{dcpo_setup} for use with Claassen's
#' Stan files for "Estimating Smooth Country-Year Panels for Public Opinion" (_Political Analysis_,
#' 2019).  Following Claassen, it dichotomizes variables by coding responses above the midpoint of
#' the response scale as 1.
#'
#' @return a list of Stan data
#'
#' @import dplyr
#' @importFrom stats median
#'
#' @export

format_claassen <- function(dcpo_data) {
    # satisfy R CMD check
    country <- year <- item <- r <- n <- survey <- x <- NULL

    # dichotomize (values above midpoint coded 1)
    dat <- dcpo_data %>%
        group_by(country, year, item) %>%
        mutate(median_r = median(r)) %>%
        summarize(x = sum(ifelse(r > median_r, n, 0)),
                  samp = sum(n),
                  survey = first(survey)) %>%
        ungroup() %>%
        filter(x > 0)

    claassen_stan <- list(  N       = nrow(dat),
                            K       = dplyr::n_distinct(dat$item),
                            T       = max(dat$year) - min(dat$year) + 1,
                            J       = dplyr::n_distinct(dat$country),
                            P       = max(as.numeric(as.factor(paste(dat$country, dat$item)))),
                            jj      = as.numeric(as.factor(dat$country)),
                            kk      = as.numeric(as.factor(dat$item)),
                            tt      = as.numeric(as.factor(dat$year)),
                            pp      = as.numeric(as.factor(paste(dat$country, dat$item))),
                            x       = round(dat$x),
                            samp    = round(dat$samp),
                            data    = dat)

    return(claassen_stan)
}
