#' Format DCPO Data for Estimation Using DGIRT Stan Files
#'
#'  \code{format_dgirt} formats DCPO data output by \code{dcpo_setup} for use with the \code{dgo}
#'  package's \code{dgirt} Stan files.
#'
#' @param dcpo_data a data frame of survey responses generated by \code{dcpo_setup}
#'
#' @return a list of Stan data
#'
#' @importFrom reshape2 acast
#' @importFrom dplyr n_distinct
#'
#' @export

format_dgirt <- function(dcpo_data) {

    n_tkqr <- reshape2::acast(dcpo_data,
                              year ~ country ~ item ~ r,
                              fun.aggregate = sum,
                              value.var = "n",
                              drop = FALSE)

    dgirt_stan <- list( G          = dplyr::n_distinct(x$country),
                        T          = max(x$year) - min(x$year) + 1,
                        Q          = dplyr::n_distinct(x$item),
                        K          = max(x$r),
                        D          = 1,
                        N          = n_tkqr,
                        beta_sign  = matrix(1, dplyr::n_distinct(x$item), 1),
                        unused_cut = unused_cp,
                        N_nonzero  = sum(n_tkqr != 0)
    )

    return(dgirt_stan)
}
